## Regs¡ister user 

POST http://127.0.0.1:8000/api/users/
Host: localhost:8080 
Content-Type: application/json

{
    "username": "qp",
    "email": "qp@a.com",
    "password": "abc12345",
    "phone": "1234567890",
    "name": "Enrique"
}


### Login user 

POST http://127.0.0.1:8000/api/users/login/ HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "username": "qp",
    "password": "abc12345"
}

### Get user profile

GET http://127.0.0.1:8000/api/users/me/ HTTP/1.1
Host: localhost:8080
Cookie: session=8ab88991331ce2374ec9c2bc5e9e6c1494a02b8a

# Fix error when cookie not found  -> 401 = not logged in

### Update user profile

PUT http://127.0.0.1:8000/api/users/me/update/ HTTP/1.1
Host: localhost:8080
Cookie: session=8ab88991331ce2374ec9c2bc5e9e6c1494a02b8a
Content-Type: application/json

{
    "name": "no",
    "phone": "0987654321"
}


### Logout user

DELETE http://127.0.0.1:8000/api/users/logout/ HTTP/1.1
Host: localhost:8080
Cookie: session=42c73e165bd80151daedb7ff9e98e0bf0d165159


### Delete user
DELETE http://127.0.0.1:8000/api/users/me/destroy/ HTTP/1.1
Host: localhost:8080
Cookie: session=0832cc77f369d94fbbff04de8de7b81f469bf645
