## Regs¡ister user 

POST http://127.0.0.1:8000/api/users/
Host: localhost:8080 
Content-Type: application/json

{
    "username": "qp",
    "email": "qp@a.com",
    "password": "abc12345",
    "phone": "1234567890",
    "name": "Enrique",
    "admin": true
}


### Login user 

POST http://127.0.0.1:8000/api/users/login/ HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "username": "qp",
    "password": "abc12345"
}

### Get user profile

GET http://127.0.0.1:8000/api/users/me/profile HTTP/1.1
Host: localhost:8080
Cookie: session=3d4b3d3bb52b5f4f890e777e3f352ec1a628af12

# Fix error when cookie not found  -> 401 = not logged in

### Update user profile

PATCH http://127.0.0.1:8000/api/users/me/update/ HTTP/1.1
Host: localhost:8080
Cookie: session=3d4b3d3bb52b5f4f890e777e3f352ec1a628af12
Content-Type: application/json

{
    "name": "no",
    "phone": "0987654321"
}


### Logout user

DELETE http://127.0.0.1:8000/api/users/logout/ HTTP/1.1
Host: localhost:8080
Cookie: session=3d4b3d3bb52b5f4f890e777e3f352ec1a628af12


### Delete user
DELETE http://127.0.0.1:8000/api/users/me/destroy/ HTTP/1.1
Host: localhost:8080
Cookie: session=56b181f5ea725d0f66d47c597542b2e9b238dbff


### Get all users
GET http://127.0.0.1:8000/api/users/list/ HTTP/1.1
Host: localhost:8000
Cookie: session=ad


### Patch user by admin and user

PATCH http://127.0.0.1:8000/api/users/me/update/admin2234/ HTTP/1.1
Host: localhost:8080
Cookie: session=56b181f5ea725d0f66d47c597542b2e9b238dbff
Content-Type: application/json

{
    "name": "nop",
    "phone": "0987654321"
}



