# Generated by Django 4.2.11 on 2024-05-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="user_reviews",
            field=models.JSONField(default=dict),
        ),
    ]
